---
output: html_document
---

# Practical Machine Learning: Prediction Assignment Writeup

Sagi Greenstine

## Introduction

Using devices such as *Jawbone Up*, *Nike FuelBand*, and *Fitbit* it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify **how much** of a particular activity they do, but they rarely quantify **how well** they do it.  
In this project, the goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants.  
Six young health participants were asked to perform one set of 10 repetitions of the Unilateral Dumbbell Biceps Curl in five different fashions: exactly according to the specification (Class A), throwing the elbows to the front (Class B), lifting the dumbbell only halfway (Class C), lowering the dumbbell only halfway (Class D) and throwing the hips to the front (Class E). Class A corresponds to the specified execution of the exercise, while the other 4 classes correspond to common mistakes.  
More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset).  
The goal of the project is to predict the manner in which they did the exercise. This is the "classe" variable in the training set. It is possible to use any of the other variables to predict with. It is necessary to create a report describing how was built the model, how was used cross validation, what the expected out of sample error is, and why were made the choices that were made. The prediction model also should be used to predict 20 different test cases. 
   
## Data Processing

### Loading and viewing the data

#### The "Weight Lifting Exercises Dataset"

**Source:** Velloso, E.; Bulling, A.; Gellersen, H.; Ugulino, W.; Fuks, H. Qualitative Activity Recognition of Weight Lifting Exercises. Proceedings of 4th International Conference in Cooperation with SIGCHI (Augmented Human '13). Stuttgart, Germany: ACM SIGCHI, 2013.

Loading the dataset:

```{r loaddata}
if(!exists("training")){
        training <- read.csv("./pml-training.csv", row.names = NULL, check.names=F, stringsAsFactors=F, header=T, sep=',', comment.char="", quote='\"', na.strings = c("NA", ""))
}
if(!exists("testing")){
        testing <- read.csv("./pml-testing.csv", row.names = NULL, check.names=F, stringsAsFactors=F, header=T, sep=',', comment.char="", quote='\"', na.strings = c("NA", ""))
}
```

The structure of the data:
training dataset 19622 obs. of  160 variables
testing dataset  20 obs. of  160 variables

The training dataset has 19622 observations and 160 variables, and the testing data set contains 20 observations and the same variables as the training set. We are trying to predict the outcome of the variable classe in the training set.

## Data Analysis



## The conclusions and the assumptions


